const {test}=require('node:test');const assert=require('node:assert/strict');const {Game,RaceRules,swept,crossed,point,position,forward,add,mul}=require('../Web/core.js');
function running(p=0){const g=new Game();g.select(p);g.start();for(let i=0;i<181;i++)g.tick(1/60);return g}
function step(g,n,input={throttle:true}){for(let i=0;i<n;i++)g.tick(1/60,input)}
test('12 ordered gates required; reverse progress rejected; finish clamped',()=>{const r=new RaceRules();r.advance(5399);assert.equal(r.gates,11);assert.equal(r.finished,false);r.advance(-500);assert.equal(r.progress,5399);r.advance(100);assert.equal(r.progress,5400);assert.equal(r.lap,3);assert.equal(r.finished,true)});
test('track seam and wrapped pad crossing',()=>{assert.ok(Math.hypot(...point(0).map((v,i)=>v-point(1800)[i]))<.001);assert.equal(crossed(1799,1802,0),true);assert.equal(crossed(1801,1802,0),false)});
test('all three pilots can complete an actual three-lap simulated race',()=>{for(let i=0;i<3;i++){const g=running(i);step(g,7200,{throttle:true,boost:true,fire:true,ability:true});assert.equal(g.state,'finished');assert.equal(g.player.race.gates,12);assert.ok(g.rank()>=1&&g.rank()<=6);assert.ok(g.stats.jumps>=6);assert.ok(g.stats.pads>=10)}});
test('driving, steering, drifting, air control and braking',()=>{const g=running();step(g,150);assert.ok(g.player.speed>70);step(g,15,{throttle:true,steer:1,drift:true});assert.ok(g.player.drifting);assert.ok(g.player.lane>0);g.player.lane=0;g.player.race.progress=319;g.player.speed=80;step(g,2);assert.ok(g.player.height>0);const lane=g.player.lane;step(g,6,{throttle:true,steer:-1});assert.ok(g.player.lane<lane+1);const speed=g.player.speed;step(g,30,{brake:true});assert.ok(g.player.speed<speed)});
test('boost is consumed and regenerates; centered pad adds velocity',()=>{const g=running();g.pads=[];step(g,180,{throttle:true,boost:true});assert.ok(g.player.boost<30);assert.ok(g.player.speed>90);step(g,120);assert.ok(g.player.boost>30);g.pads=[80];g.player.race.progress=79;g.player.lane=0;g.player.speed=78;step(g,2);assert.ok(g.player.speed>110)});
test('shield absorbs first, hull takes overflow, destruction recovers at gate',()=>{const g=running(),p=g.player;p.race.advance(700);g.damage(p,120);assert.equal(p.shield,0);assert.equal(p.hull,80);g.damage(p,100);assert.equal(p.race.progress,450);assert.equal(p.hull,100);assert.ok(p.immune>0);assert.equal(p.speed,0)});
test('all abilities, cooldown gating and immunity',()=>{for(let i=0;i<3;i++){const g=running(i),p=g.player;p.shield=20;p.boost=10;g.ability(p);assert.equal(p.cooldown,14);if(i===0){assert.equal(p.shield,65);g.damage(p,200);assert.equal(p.hull,100)}if(i===1)assert.equal(p.ability,5);if(i===2){assert.equal(p.boost,100);assert.equal(p.immune,4)}g.ability(p);assert.equal(p.cooldown,14)}});
test('laser and missile damage drone using swept projectile hits',()=>{const g=running(),p=g.player;g.racers=[p];g.drones=[{s:35,lane:0,hp:60,respawn:0,fire:99}];p.lane=0;g.fire(p,true);step(g,70,{fire:true});assert.ok(p.kills>=1);assert.ok(g.stats.hits>=1);assert.equal(p.ammo,2);assert.equal(swept([0,0,0],[0,0,100],[0,0,50],2),true)});
test('empty missile inventory and rate limit prevent free missiles',()=>{const g=running(),p=g.player;g.fire(p,true);g.fire(p,true);assert.equal(p.ammo,2);p.ammo=0;p.missile=0;const n=g.shots.length;g.fire(p,true);assert.equal(g.shots.length,n)});
test('pickups collect once then respawn',()=>{const g=running(),p=g.player;g.racers=[p];g.drones=[];g.pickups=[{s:1,lane:0,type:0,timer:0}];p.lane=0;step(g,1,{});assert.equal(p.ammo,6);step(g,30,{});assert.equal(p.ammo,6);assert.equal(g.stats.pickups,1);step(g,500,{});assert.equal(p.ammo,9)});
test('pause freezes all simulation; restart clears race state',()=>{const g=running();step(g,60);g.pause();const progress=g.player.race.progress,time=g.time;step(g,120);assert.equal(g.player.race.progress,progress);assert.equal(g.time,time);g.pause();step(g,60);assert.ok(g.time>time);g.start();assert.equal(g.time,0);assert.equal(g.shots.length,0);assert.equal(g.player.kills,0);assert.equal(g.state,'countdown')});

test("brake takes priority over throttle",()=>{const g=running();g.pads=[];step(g,120);const speed=g.player.speed;step(g,20,{throttle:true,brake:true});assert.ok(g.player.speed<speed-20)});
