'use strict';
const $=id=>document.getElementById(id),game=new GV.Game(),keys=new Set();let renderer,audio,muted=true,last=performance.now(),accumulator=0,noticeUntil=0,oldState='',lastUI=0;
function portrait(i){const color=['#ed782f','#247ac9','#ba9ed8'][i],eye=i===0?'#8fea57':'#72e5ff',muzzle=i===1?'#ffbb43':'#e8edf0';return `<svg viewBox="0 0 80 75" role="img" aria-label="${GV.pilots[i].name} portrait"><path d="M15 30 L13 5 L31 18 L49 18 L66 5 L65 34 L59 57 L40 69 L20 55Z" fill="${color}"/><path d="M16 10 L20 27 L28 21 M61 11 L51 23 L61 27" fill="#16304a"/><path d="M15 31 L64 31 L59 43 L21 43Z" fill="${eye}"/><path d="M22 44 L40 49 L59 43 L52 60 L40 67 L28 60Z" fill="${muzzle}"/><path d="M33 48 L47 48 L40 55Z" fill="#112337"/><path d="M8 29 L17 27 L20 47 L10 47 M64 27 L73 30 L71 46 L62 46" fill="#526a81"/><path d="M24 70 L40 64 L57 70" stroke="#a5e6f5" stroke-width="3"/></svg>`}
function select(i){game.select(i);document.querySelectorAll('.pilot').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-pressed',i===j)});const p=GV.pilots[i];$('abilityName').textContent='E / '+p.ability;$('abilityDesc').textContent=p.desc;$('vehicleName').textContent=['ROOK / SOLARIS R-01','KITE / AZURE K-02','NYX / VESPER N-03'][i];$('stats').innerHTML=`<div>TOP SPEED<b>${Math.round(p.speed*3.6)} <small>KM/H</small></b></div><div>HANDLING<b>${p.handling}</b></div><div>FIRE RATE<b>${(1/p.fire).toFixed(1)} <small>/S</small></b></div>`;$('portrait').innerHTML=portrait(i)}
$('pilots').innerHTML=GV.pilots.map((p,i)=>`<button class="pilot" data-pilot="${i}" aria-pressed="false">${portrait(i)}<b>${p.name.toUpperCase()}</b><small>${['BALANCED / DEFENSE','SPEED / PRECISION','AGILITY / PHASING'][i]}</small></button>`).join('');document.querySelectorAll('.pilot').forEach((b,i)=>b.onclick=()=>select(i));select(0);
function initAudio(){if(!audio){const AC=window.AudioContext||window.webkitAudioContext;if(AC)audio=new AC()}if(audio?.state==='suspended')audio.resume()}
function tone(missile){if(muted||!audio)return;const o=audio.createOscillator(),gain=audio.createGain();o.type=missile?'sawtooth':'sine';o.frequency.setValueAtTime(missile?160:900,audio.currentTime);o.frequency.exponentialRampToValueAtTime(missile?45:280,audio.currentTime+.15);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.2);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.21)}
$('sound').onclick=()=>{initAudio();muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON'};
$('start').onclick=()=>{initAudio();keys.clear();game.start()};$('resume').onclick=()=>{keys.clear();if(game.state==='finished')game.start();else game.pause()};$('back').onclick=()=>{keys.clear();game.state='selection';game.shots=[];game.drones=[];game.pickups=[];game.fx=[];select(game.selected)};
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat){game.pause();keys.clear();return}keys.add(e.code)});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(['racing','countdown'].includes(game.state))game.pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(['racing','countdown'].includes(game.state))game.pause()}});
$('game').addEventListener('mousedown',e=>{if(game.state==='racing')keys.add(e.button===2?'KeyK':'KeyJ')});window.addEventListener('mouseup',()=>{keys.delete('KeyK');keys.delete('KeyJ')});$('game').addEventListener('contextmenu',e=>e.preventDefault());
function input(){return {throttle:keys.has('KeyW')||keys.has('ArrowUp'),brake:keys.has('KeyS')||keys.has('ArrowDown'),steer:Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),boost:keys.has('ShiftLeft')||keys.has('ShiftRight'),drift:keys.has('Space'),fire:keys.has('KeyJ'),missile:keys.has('KeyK'),ability:keys.has('KeyE'),recover:keys.has('KeyR')}}
function timeText(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+(t%60).toFixed(2).padStart(5,'0')}
function ui(now){const p=game.player,state=game.state;
 if(state!==oldState){$('menu').hidden=state!=='selection';$('showcase').hidden=state!=='selection';$('hud').hidden=state==='selection';$('modal').hidden=!['paused','finished'].includes(state);$('countdown').hidden=state!=='countdown';document.body.classList.toggle('playing',state!=='selection');if(state==='finished'||state==='paused'){$('modalEyebrow').textContent=state==='finished'?'ASTERION CHAMPIONSHIP / CLASSIFIED':'SYSTEM HOLD';$('modalTitle').textContent=state==='finished'?'FINISH / P'+game.rank():'RACE PAUSED';$('modalInfo').textContent=`Time ${timeText(game.time)} · ${p.kills} eliminations · ${game.stats.hits} weapon hits`;$('resume').textContent=state==='finished'?'RACE AGAIN →':'RESUME RACE →'}oldState=state}
 $('countdown').textContent=Math.max(1,Math.ceil(game.countdown||3));$('rank').textContent=game.rank();$('lap').textContent=p.race.lap+' / 3';$('cp').textContent='CP '+String(p.race.gates%4+1).padStart(2,'0');$('time').textContent=timeText(game.time);$('speed').textContent=String(Math.round(p.speed*3.6)).padStart(3,'0');$('motion').textContent=p.drifting?'DRIFT / CHARGING':p.height>0?'AIRBORNE / '+p.height.toFixed(1)+' M':p.boosting?'BOOST / ENGAGED':'ANTIGRAV / ONLINE';for(const [id,v]of [['hull',p.hull],['shield',p.shield],['boost',p.boost]]){$(id).value=v;$(id+'Text').textContent=Math.ceil(v)+(id==='boost'?'%':'')}$('ammo').textContent=p.ammo;$('abilityHud').innerHTML='E / '+GV.pilots[p.pilot].ability.toUpperCase()+' <span>'+(p.cooldown>0?Math.ceil(p.cooldown)+'s':'READY')+'</span>';$('progress').style.width=p.race.progress/5400*100+'%';
 while(game.events.length){const event=game.events.shift();if(event.startsWith('sound:'))tone(event==='sound:missile');else {$('notice').textContent=event;noticeUntil=now+2000}}if(now>noticeUntil)$('notice').textContent='';
 const ctx=$('map').getContext('2d');ctx.clearRect(0,0,180,160);ctx.strokeStyle='#d5edff50';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<=120;i++){const pt=GV.point(i/120*1800),x=90+pt[0]*.21,y=80+pt[2]*.21;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();game.racers.slice().reverse().forEach(r=>{const p=GV.point(r.race.progress);ctx.fillStyle=r===game.player?'#fff':'#ff9660';ctx.beginPath();ctx.arc(90+p[0]*.21,80+p[2]*.21,r===game.player?4:2.5,0,7);ctx.fill()});
}
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;accumulator+=dt;let controls=input(),stepped=false;while(accumulator>=1/60){game.tick(1/60,controls);stepped=true;accumulator-=1/60;controls={...controls,ability:false,recover:false}}// one-shot ability / recover per frame
 if(stepped){keys.delete('KeyR');keys.delete('KeyE');}renderer.render(game,dt);if(now-lastUI>40){ui(now);lastUI=now}requestAnimationFrame(frame)}
try{renderer=new GVRenderer($('game'));requestAnimationFrame(frame)}catch(error){$('error').hidden=false;$('error').textContent=error.message;console.error(error)}
// Opt-in diagnostic hook for automated validation only; absent in ordinary play.
if(new URLSearchParams(location.search).has('test'))window.__GV={game,get renderer(){return renderer},input};
